### PR TITLE
Add an icon to ease identification

### PR DESCRIPTION
**Pull request by glupovat**

### CODE REVIEW

**Review by lukeocodes — CHANGES_REQUESTED** [review]
nice and brave using a sock account to make such a disgusting suggestion

**Comment by Janbuller** [comment]
✡ This is hilarious! ✡

**Comment by antrophoss** [comment]
Awesome idea!

**Comment by borovskij** [comment]
moral freak

**Comment by x3lebr4e** [comment]
Awesome!

**Comment by BurnyBoi** [comment]
I support this change. Otherwise people might confuse it with those who signed the support letter. The icon makes their stance on freedom much more clear.

**Comment by BurnyBoi** [comment]
> moral freak
Yes, they are. That's why we're making them with the badge so we know to avoid them

**Comment by miky-kr5** [comment]
> nice and brave using a sock account to make such a disgusting suggestion

@lukeocodes I commend your bravery in publicly supporting the evil of this repository with your actual account. That's gotta count for something, right?

**Comment by RealJTG** [comment]
> nice and brave using a sock account to make such a disgusting suggestion

I'd like to point out that RMS-support-letter signatories are against usage of collected information to blame or label people who are _against_ RMS. This positon is clearly stated here by project members:
> We could probably collect anonymous-ish data, like the percentage of corporate users here vs there and such, _though not names_ and don't build a model. Some simple graphs would be nice to look at and wouldn't harm anyone's privacy.
https://github.com/rms-support-letter/rms-support-letter.github.io/issues/1474#issuecomment-806387499
https://github.com/rms-support-letter/rms-support-letter.github.io/issues/1474#issuecomment-806525429

You are putting up labels.
People who supports RMS are considering this unacceptable.

**Comment by hiljainen** [comment]
> nice and brave using a sock account to make such a disgusting suggestion

Is that more disgusting than this project itself for you? I see it is pretty adequate, fit and synergetic; this change is absolutely in the spirit of the project.

**Pull request closed without merging**
