### PR TITLE
Fixed the list

### PR DESCRIPTION
**Pull request by ExtReMLapin**

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
Some signatures can be anonymous but you can still find the user identity, for example, 3 github employees signed it


```JSON
  {
    "email": "omgjlk@github.com",
    "name": "Jesse Keating",
    "type": "Anonymous",
    "contributions": 1
  },
    {
    "email": "ktravers@github.com",
    "name": "Kate Travers",
    "type": "Anonymous",
    "contributions": 1
  },
  {
    "email": "sarahkemi@github.com",
    "name": "Sarah Aladetan",
    "type": "Anonymous",
    "contributions": 1
  },
```

**Comment by shenlebantongying** [comment]
I reviewed these commits and I think they should be merged to the main repository.

**Review by lukeocodes — CHANGES_REQUESTED** [review]
Derp

**Review by aspenluxxxy — CHANGES_REQUESTED** [review]
cring comp

**Comment by ExtReMLapin** [comment]
mister @aspenluxxxy this is not a place to post shit memes

**Comment by aspenluxxxy** [comment]
Y'know, it really says something that Stallman supporters are the ones harassing and trying to irritate the people who _don't_ support him.

**Comment by ExtReMLapin** [comment]
1. Someone decides to make a letter against stallman
2. A group of person decides to make a letter supporting him, this letter gets much more signature
3. first group decides to [make a list of those persons and be able to recognize them by adding a "badge"](https://en.wikipedia.org/wiki/Yellow_badge)
4. A random guy (me) who didn't sign any of the letters decides to also make a list of the first group, to be sure no one gets left behind ;) 

And i'm the guy harrasing people ?
Sir, this is funny you decide to call the second group and I "harassers" yet I and they didn't do anything the first group didn't do.

The anti-RMS letters breaks Github ToS/Community guidlines and breaks multiple federal laws in the US, yet you only complain here about me and not even about the people making lists of people they don't like ?


if you get "somehow" abducted by aliens, just tell them you're not human okay, do not throw shame on our species with your poor judgment skills.

**Comment by ExtReMLapin** [comment]
Also how can you say i'm harrassing anyone, I even added in the "README.me" that the repo will go down if the signature one does, how is it not a proof of being against harrasment ????

**Comment by aspenluxxxy** [comment]
>    Someone decides to make a letter against stallman
>    A group of person decides to make a letter supporting him, this letter gets much more signature
>    first group decides to make a list of those persons and be able to recognize them by adding a "badge"
>    A random guy (me) who didn't sign any of the letters decides to also make a list of the first group, to be sure no one gets left behind ;)

Have you considered the option that has less drama - making your own independent repo and doing that? PRing it here is intended _solely_ to stir shit up and piss people off.

Oh wait, I forgot the Stallman way is to "show up out of nowhere when someone does something you don't like, complain endlessly without any actual satisfying solution, then leave and repeat"

> And i'm the guy harrasing people ?
> Sir, this is funny you decide to call the second group and I "harassers" yet I and they didn't do anything the first group didn't do.

Maybe not you, but ***some*** people certainly are, and you're fueling the flames.

There's [SOMEONE](https://github.com/shenlebantongying) doing a bunch of attempted harassment though, and people sure are supporting their harassment, though.

> The anti-RMS letters breaks Github ToS/Community guidlines and breaks multiple federal laws in the US

I'd like to have a concrete answer what these are, if you may.

**Comment by lukeocodes** [comment]
@aspenluxxxy you're talking to the same folks PRing the Star of David into buttons... it literally isn't worth the effort.

**Comment by aspenluxxxy** [comment]
@lukeocodes good point.

**Comment by ExtReMLapin** [comment]
>I'd like to have a concrete answer what these are, if you may.
You can find a good report : https://gist.github.com/ExtReMLapin/cb5287b0d6987243e72ffdec88ddb153
Not wrote by me, the very last part is very subjective (part where the lady who opened the repo need to resign)

**Comment by aspenluxxxy** [comment]
@ExtReMLapin Sooo... that paper's entire argument revolves around "false statements"...

You're saying that arguments _that cite archives of RMS' own personal website_ are false.

The other guy was right, this isn't worth the effort at all.

**Comment by JackRedstonia** [comment]
@aspenluxxxy Don't be a dick. Especially after you lost yours.

**Comment by aspenluxxxy** [comment]
That was an unnecessary comment which only made yourself look bad.

**Comment by JackRedstonia** [comment]
I'm sorry but you're making transgender people look bad by making a fool of yourself. I respect transgender people, not dicks.

**Comment by ExtReMLapin** [comment]
personnal attacks are against github community guidelines, pls no bully on my issue @JackRedstonia

**Pull request closed without merging**
